#!/usr/bin/env node
// Regenerates every collection from openapi.json. No dependencies, no build step.
//
//   node scripts/generate.mjs            regenerate in place
//   node scripts/generate.mjs --check    fail if the output is stale (CI)

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatePostman } from './generate-postman.mjs';
import { generateBruno } from './generate-bruno.mjs';
import { groupByTag, loadSpec, rebrand } from './lib/spec.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

/** Every generated file, keyed by path relative to the repo, for the staleness check. */
function snapshot(...targets) {
  const files = new Map();
  const visit = (target) => {
    let stats;
    try {
      stats = statSync(target);
    } catch {
      return;
    }
    if (stats.isDirectory()) {
      for (const entry of readdirSync(target)) visit(join(target, entry));
      return;
    }
    files.set(target.slice(root.length + 1), readFileSync(target, 'utf8'));
  };
  targets.forEach(visit);
  return files;
}

const existing = check
  ? snapshot(join(root, 'postman'), join(root, 'bruno'), join(root, 'ENDPOINTS.md'))
  : new Map();

const spec = loadSpec(join(root, 'openapi.json'));

const postman = generatePostman(spec, join(root, 'postman'));
const bruno = generateBruno(spec, join(root, 'bruno'));

// A browsable index so the endpoint list is readable on GitHub without an API client.
const groups = groupByTag(spec);
const lines = [
  '# Endpoints',
  '',
  `<!-- Generated by scripts/generate.mjs. Do not edit. -->`,
  '',
  `${postman} operations across ${groups.size} groups, from OpenAPI ${spec.openapi}, API version ${spec.info.version}.`,
  '',
];
for (const [tag, entries] of groups) {
  lines.push(`## ${tag}`, '');
  lines.push('| Method | Path | Operation | Scope |', '| --- | --- | --- | --- |');
  for (const { method, path, op } of entries) {
    const scope = op['x-owlstack-scope'] ? `\`${op['x-owlstack-scope']}\`` : '—';
    lines.push(
      `| ${method.toUpperCase()} | \`${path}\` | ${rebrand(op.summary ?? op.operationId ?? '')} | ${scope} |`,
    );
  }
  lines.push('');
}
writeFileSync(join(root, 'ENDPOINTS.md'), `${lines.join('\n')}`);

console.log(`postman: ${postman} requests`);
console.log(`bruno:   ${bruno} requests`);

if (check) {
  const before = snapshot(join(root, 'postman'), join(root, 'bruno'), join(root, 'ENDPOINTS.md'));
  const stale = [...before]
    .filter(([file, content]) => existing.get(file) !== content)
    .map(([file]) => file);
  const removed = [...existing.keys()].filter((file) => !before.has(file));
  const drift = [...new Set([...stale, ...removed])].sort();
  if (drift.length) {
    console.error(
      `\nGenerated output is stale. Run \`npm run generate\` and commit:\n${drift
        .map((f) => `  ${f}`)
        .join('\n')}`,
    );
    process.exit(1);
  }
  console.log('check: collections are in sync with openapi.json');
}
